framework:
    secret: secret
    form:
        enabled: true
    validation:
        enabled: true

doctrine:
    dbal:
        driver:   pdo_sqlite
        path: %kernel.root_dir%/app.sqlite
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

doctrine_phpcr:
    session:
        backend:
            type: doctrinedbal
        workspace: default
        username: admin
        password: admin

    odm:
        auto_mapping: true

psi_content_type:
    storage_drivers: 
        - doctrine_phpcr_odm

services:
    example_content_type:
        class: Psi\Bundle\ContentType\Example\src\ExampleField
        tags: 
            - { name: psi_content_type.field, alias: example }
